### ISSUE TITLE
Function breaks on infinite values

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsBalancing#2]
```
> balancingNormal(Inf, Inf, -1)

Error during wrapup: missing value where TRUE/FALSE needed
```

This situation comes up during Standardization and so the code breaks [here](https://github.com/SWS-Methodology/faoswsBalancing/blob/master/R/balancingNormal.R#L59) and on the following line.

**Comment by marcosmilzo** [comment]
Balancing will stop if any Inf value is present

**Comment by sebastian-c** [comment]
This issue corresponds to SWS-Methodology/faoswsStandardization#18
